apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: vote-worker
  name: vote-worker
  namespace: test
spec:
  ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: vote-worker
    deploymentconfig: vote-worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}