apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: web-vote-app
  name: web-vote-app
  namespace: test
spec:
  ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: web-vote-app
    deploymentconfig: web-vote-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}