apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: redis
  name: redis
  namespace: test
spec:
  ports:
    - name: 6379-tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
    deploymentconfig: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}